// ARK creature color definitions derived from ARK Smart Breeding's MIT-licensed ASE and ASA values data.
// Includes the ASA dye-derived creature colors at IDs 128–254; hex swatches are converted from linear RGB to sRGB.
globalThis.ARK_COLOR_DATA = Object.freeze([
  Object.freeze({ id: 0, name: "No color / unused", hex: "#777777" }),
  Object.freeze({ id: 1, name: "Red", hex: "#FF0000" }),
  Object.freeze({ id: 2, name: "Blue", hex: "#0000FF" }),
  Object.freeze({ id: 3, name: "Green", hex: "#00FF00" }),
  Object.freeze({ id: 4, name: "Yellow", hex: "#FFFF00" }),
  Object.freeze({ id: 5, name: "Cyan", hex: "#00FFFF" }),
  Object.freeze({ id: 6, name: "Magenta", hex: "#FF00FF" }),
  Object.freeze({ id: 7, name: "Light Green", hex: "#C0FFBA" }),
  Object.freeze({ id: 8, name: "Light Grey", hex: "#C8CACA" }),
  Object.freeze({ id: 9, name: "Light Brown", hex: "#786759" }),
  Object.freeze({ id: 10, name: "Light Orange", hex: "#FFB46C" }),
  Object.freeze({ id: 11, name: "Light Yellow", hex: "#FFFA8A" }),
  Object.freeze({ id: 12, name: "Light Red", hex: "#FF756C" }),
  Object.freeze({ id: 13, name: "Dark Grey", hex: "#7B7B7B" }),
  Object.freeze({ id: 14, name: "Black", hex: "#3B3B3B" }),
  Object.freeze({ id: 15, name: "Brown", hex: "#593A2A" }),
  Object.freeze({ id: 16, name: "Dark Green", hex: "#224900" }),
  Object.freeze({ id: 17, name: "Dark Red", hex: "#812118" }),
  Object.freeze({ id: 18, name: "White", hex: "#FFFFFF" }),
  Object.freeze({ id: 19, name: "Dino Light Red", hex: "#FFA8A8" }),
  Object.freeze({ id: 20, name: "Dino Dark Red", hex: "#592B2B" }),
  Object.freeze({ id: 21, name: "Dino Light Orange", hex: "#FFB694" }),
  Object.freeze({ id: 22, name: "Dino Dark Orange", hex: "#88532F" }),
  Object.freeze({ id: 23, name: "Dino Light Yellow", hex: "#CACAA0" }),
  Object.freeze({ id: 24, name: "Dino Dark Yellow", hex: "#94946C" }),
  Object.freeze({ id: 25, name: "Dino Light Green", hex: "#E0FFE0" }),
  Object.freeze({ id: 26, name: "Dino Medium Green", hex: "#799479" }),
  Object.freeze({ id: 27, name: "Dino Dark Green", hex: "#224122" }),
  Object.freeze({ id: 28, name: "Dino Light Blue", hex: "#D9E0FF" }),
  Object.freeze({ id: 29, name: "Dino Dark Blue", hex: "#394263" }),
  Object.freeze({ id: 30, name: "Dino Light Purple", hex: "#E4D9FF" }),
  Object.freeze({ id: 31, name: "Dino Dark Purple", hex: "#403459" }),
  Object.freeze({ id: 32, name: "Dino Light Brown", hex: "#FFE0BA" }),
  Object.freeze({ id: 33, name: "Dino Medium Brown", hex: "#948575" }),
  Object.freeze({ id: 34, name: "Dino Dark Brown", hex: "#594E41" }),
  Object.freeze({ id: 35, name: "Dino Darker Grey", hex: "#595959" }),
  Object.freeze({ id: 36, name: "Dino Albino", hex: "#FFFFFF" }),
  Object.freeze({ id: 37, name: "BigFoot0", hex: "#B79683" }),
  Object.freeze({ id: 38, name: "BigFoot4", hex: "#EADAD5" }),
  Object.freeze({ id: 39, name: "BigFoot5", hex: "#D0A794" }),
  Object.freeze({ id: 40, name: "WolfFur", hex: "#C3B39F" }),
  Object.freeze({ id: 41, name: "DarkWolfFur", hex: "#887666" }),
  Object.freeze({ id: 42, name: "DragonBase0", hex: "#A0664B" }),
  Object.freeze({ id: 43, name: "DragonBase1", hex: "#CB7956" }),
  Object.freeze({ id: 44, name: "DragonFire", hex: "#BC4F00" }),
  Object.freeze({ id: 45, name: "DragonGreen0", hex: "#79846C" }),
  Object.freeze({ id: 46, name: "DragonGreen1", hex: "#909C79" }),
  Object.freeze({ id: 47, name: "DragonGreen2", hex: "#A5A48B" }),
  Object.freeze({ id: 48, name: "DragonGreen3", hex: "#74939C" }),
  Object.freeze({ id: 49, name: "WyvernPurple0", hex: "#787496" }),
  Object.freeze({ id: 50, name: "WyvernPurple1", hex: "#B0A2C0" }),
  Object.freeze({ id: 51, name: "WyvernBlue0", hex: "#6281A7" }),
  Object.freeze({ id: 52, name: "WyvernBlue1", hex: "#485C75" }),
  Object.freeze({ id: 53, name: "Dino Medium Blue", hex: "#5FA4EA" }),
  Object.freeze({ id: 54, name: "Dino Deep Blue", hex: "#4568D4" }),
  Object.freeze({ id: 55, name: "NearWhite", hex: "#EDEDED" }),
  Object.freeze({ id: 56, name: "NearBlack", hex: "#515151" }),
  Object.freeze({ id: 57, name: "DarkTurquoise", hex: "#184546" }),
  Object.freeze({ id: 58, name: "MediumTurquoise", hex: "#007060" }),
  Object.freeze({ id: 59, name: "Turquoise", hex: "#00C5AB" }),
  Object.freeze({ id: 60, name: "GreenSlate", hex: "#40594C" }),
  Object.freeze({ id: 61, name: "Sage", hex: "#3E4F40" }),
  Object.freeze({ id: 62, name: "DarkWarmGray", hex: "#3B3938" }),
  Object.freeze({ id: 63, name: "MediumWarmGray", hex: "#585554" }),
  Object.freeze({ id: 64, name: "LightWarmGray", hex: "#9B9290" }),
  Object.freeze({ id: 65, name: "DarkCement", hex: "#525B56" }),
  Object.freeze({ id: 66, name: "LightCement", hex: "#8AA196" }),
  Object.freeze({ id: 67, name: "LightPink", hex: "#E8B0FF" }),
  Object.freeze({ id: 68, name: "DeepPink", hex: "#FF119A" }),
  Object.freeze({ id: 69, name: "DarkViolet", hex: "#730046" }),
  Object.freeze({ id: 70, name: "DarkMagenta", hex: "#B70042" }),
  Object.freeze({ id: 71, name: "BurntSienna", hex: "#7E331E" }),
  Object.freeze({ id: 72, name: "MediumAutumn", hex: "#A93000" }),
  Object.freeze({ id: 73, name: "Vermillion", hex: "#EF3100" }),
  Object.freeze({ id: 74, name: "Coral", hex: "#FF5834" }),
  Object.freeze({ id: 75, name: "Orange", hex: "#FF7F00" }),
  Object.freeze({ id: 76, name: "Peach", hex: "#FFA73A" }),
  Object.freeze({ id: 77, name: "LightAutumn", hex: "#AE7000" }),
  Object.freeze({ id: 78, name: "Mustard", hex: "#949427" }),
  Object.freeze({ id: 79, name: "ActualBlack", hex: "#171717" }),
  Object.freeze({ id: 80, name: "MidnightBlue", hex: "#191D36" }),
  Object.freeze({ id: 81, name: "DarkBlue", hex: "#152B3A" }),
  Object.freeze({ id: 82, name: "BlackSands", hex: "#302531" }),
  Object.freeze({ id: 83, name: "LemonLime", hex: "#A8FF44" }),
  Object.freeze({ id: 84, name: "Mint", hex: "#38E985" }),
  Object.freeze({ id: 85, name: "Jade", hex: "#008840" }),
  Object.freeze({ id: 86, name: "PineGreen", hex: "#0F552E" }),
  Object.freeze({ id: 87, name: "SpruceGreen", hex: "#005B45" }),
  Object.freeze({ id: 88, name: "LeafGreen", hex: "#5B9725" }),
  Object.freeze({ id: 89, name: "DarkLavender", hex: "#5E275F" }),
  Object.freeze({ id: 90, name: "MediumLavender", hex: "#853587" }),
  Object.freeze({ id: 91, name: "Lavender", hex: "#BD77BE" }),
  Object.freeze({ id: 92, name: "DarkTeal", hex: "#0E404A" }),
  Object.freeze({ id: 93, name: "MediumTeal", hex: "#105563" }),
  Object.freeze({ id: 94, name: "Teal", hex: "#14849C" }),
  Object.freeze({ id: 95, name: "PowderBlue", hex: "#82A7FF" }),
  Object.freeze({ id: 96, name: "Glacial", hex: "#ACEAFF" }),
  Object.freeze({ id: 97, name: "Cammo", hex: "#505118" }),
  Object.freeze({ id: 98, name: "DryMoss", hex: "#766E3F" }),
  Object.freeze({ id: 99, name: "Custard", hex: "#C0BD5E" }),
  Object.freeze({ id: 100, name: "Cream", hex: "#F4FFC0" }),
  // ASA dye colors can also appear in creature regions, including through mutation. IDs 101?127 are unused.
  Object.freeze({ id: 128, name: "Burn Coloring", hex: "#330000" }),
  Object.freeze({ id: 129, name: "Scab Coloring", hex: "#660000" }),
  Object.freeze({ id: 130, name: "Gore Coloring", hex: "#B30000" }),
  Object.freeze({ id: 131, name: "Red Coloring", hex: "#FF0000" }),
  Object.freeze({ id: 132, name: "Tulip Coloring", hex: "#FF7373" }),
  Object.freeze({ id: 133, name: "Salmon Coloring", hex: "#FFBFBF" }),
  Object.freeze({ id: 134, name: "Incense Coloring", hex: "#D98D8D" }),
  Object.freeze({ id: 135, name: "Edocha Coloring", hex: "#A65353" }),
  Object.freeze({ id: 136, name: "Bronze Coloring", hex: "#331900" }),
  Object.freeze({ id: 137, name: "Terracotta Coloring", hex: "#663300" }),
  Object.freeze({ id: 138, name: "Windsor Coloring", hex: "#B35900" }),
  Object.freeze({ id: 139, name: "Orange Coloring", hex: "#FF7F00" }),
  Object.freeze({ id: 140, name: "Cantaloupe Coloring", hex: "#FFB973" }),
  Object.freeze({ id: 141, name: "Peach Coloring", hex: "#FFDFBF" }),
  Object.freeze({ id: 142, name: "Latte Coloring", hex: "#D9B38D" }),
  Object.freeze({ id: 143, name: "Dirt Coloring", hex: "#A67C53" }),
  Object.freeze({ id: 144, name: "Drab Coloring", hex: "#333300" }),
  Object.freeze({ id: 145, name: "Olive Coloring", hex: "#666600" }),
  Object.freeze({ id: 146, name: "Citron Coloring", hex: "#B2B300" }),
  Object.freeze({ id: 147, name: "Yellow Coloring", hex: "#FFFF00" }),
  Object.freeze({ id: 148, name: "Canary Coloring", hex: "#FFFF73" }),
  Object.freeze({ id: 149, name: "Buttermilk Coloring", hex: "#FFFFBF" }),
  Object.freeze({ id: 150, name: "Khaki Coloring", hex: "#D9D98D" }),
  Object.freeze({ id: 151, name: "Mold Coloring", hex: "#A6A653" }),
  Object.freeze({ id: 152, name: "Swamp Coloring", hex: "#193300" }),
  Object.freeze({ id: 153, name: "Avocado Coloring", hex: "#336600" }),
  Object.freeze({ id: 154, name: "Orc Coloring", hex: "#59B300" }),
  Object.freeze({ id: 155, name: "Chartreuse Coloring", hex: "#80FF00" }),
  Object.freeze({ id: 156, name: "Menthol Coloring", hex: "#B9FF73" }),
  Object.freeze({ id: 157, name: "Nyanza Coloring", hex: "#DFFFBF" }),
  Object.freeze({ id: 158, name: "Putrescence Coloring", hex: "#B3D98D" }),
  Object.freeze({ id: 159, name: "Filth Coloring", hex: "#7CA653" }),
  Object.freeze({ id: 160, name: "Nori Coloring", hex: "#003300" }),
  Object.freeze({ id: 161, name: "Hunter Coloring", hex: "#006600" }),
  Object.freeze({ id: 162, name: "Emerald Coloring", hex: "#00B300" }),
  Object.freeze({ id: 163, name: "Green Coloring", hex: "#00FF00" }),
  Object.freeze({ id: 164, name: "Mint Coloring", hex: "#73FF73" }),
  Object.freeze({ id: 165, name: "Pistachio Coloring", hex: "#BFFFBF" }),
  Object.freeze({ id: 166, name: "Celadon Coloring", hex: "#8DD98D" }),
  Object.freeze({ id: 167, name: "Chateau Coloring", hex: "#53A653" }),
  Object.freeze({ id: 168, name: "Jungle Coloring", hex: "#00331A" }),
  Object.freeze({ id: 169, name: "Forest Coloring", hex: "#006633" }),
  Object.freeze({ id: 170, name: "Lagoon Coloring", hex: "#00B359" }),
  Object.freeze({ id: 171, name: "Spring Coloring", hex: "#00FF80" }),
  Object.freeze({ id: 172, name: "Aquamarine Coloring", hex: "#73FFB9" }),
  Object.freeze({ id: 173, name: "Seafoam Coloring", hex: "#BFFFDF" }),
  Object.freeze({ id: 174, name: "Turquoise Coloring", hex: "#8DD9B3" }),
  Object.freeze({ id: 175, name: "Shamrock Coloring", hex: "#53A67C" }),
  Object.freeze({ id: 176, name: "Mariana Coloring", hex: "#003333" }),
  Object.freeze({ id: 177, name: "Skobeloff Coloring", hex: "#006666" }),
  Object.freeze({ id: 178, name: "Teal Coloring", hex: "#00B3B3" }),
  Object.freeze({ id: 179, name: "Cyan Coloring", hex: "#00FFFF" }),
  Object.freeze({ id: 180, name: "Electricity Coloring", hex: "#73FFFF" }),
  Object.freeze({ id: 181, name: "Celeste Coloring", hex: "#BFFFFF" }),
  Object.freeze({ id: 182, name: "Crystal Coloring", hex: "#8DD9D9" }),
  Object.freeze({ id: 183, name: "Ocean Coloring", hex: "#53A6A6" }),
  Object.freeze({ id: 184, name: "Cetecean Coloring", hex: "#001A33" }),
  Object.freeze({ id: 185, name: "Prussian Coloring", hex: "#003366" }),
  Object.freeze({ id: 186, name: "Sapphire Coloring", hex: "#0059B3" }),
  Object.freeze({ id: 187, name: "Azure Coloring", hex: "#007FFF" }),
  Object.freeze({ id: 188, name: "Babyblue Coloring", hex: "#73B9FF" }),
  Object.freeze({ id: 189, name: "Cornflower Coloring", hex: "#BFDFFF" }),
  Object.freeze({ id: 190, name: "Overcast Coloring", hex: "#8CB2D9" }),
  Object.freeze({ id: 191, name: "Moonstone Coloring", hex: "#537CA6" }),
  Object.freeze({ id: 192, name: "Midnight Coloring", hex: "#000033" }),
  Object.freeze({ id: 193, name: "Navy Coloring", hex: "#000066" }),
  Object.freeze({ id: 194, name: "Cobalt Coloring", hex: "#0000B3" }),
  Object.freeze({ id: 195, name: "Blue Coloring", hex: "#0000FF" }),
  Object.freeze({ id: 196, name: "Denim Coloring", hex: "#7373FF" }),
  Object.freeze({ id: 197, name: "Ice Coloring", hex: "#BFBFFF" }),
  Object.freeze({ id: 198, name: "Frost Coloring", hex: "#8C8CD9" }),
  Object.freeze({ id: 199, name: "Deepfreeze Coloring", hex: "#5353A6" }),
  Object.freeze({ id: 200, name: "Twilight Coloring", hex: "#190033" }),
  Object.freeze({ id: 201, name: "Eminence Coloring", hex: "#330066" }),
  Object.freeze({ id: 202, name: "Indigo Coloring", hex: "#5900B3" }),
  Object.freeze({ id: 203, name: "Violet Coloring", hex: "#8000FF" }),
  Object.freeze({ id: 204, name: "Lilac Coloring", hex: "#B973FF" }),
  Object.freeze({ id: 205, name: "Lavender Coloring", hex: "#DFBFFF" }),
  Object.freeze({ id: 206, name: "Mauve Coloring", hex: "#B38DD9" }),
  Object.freeze({ id: 207, name: "Royalty Coloring", hex: "#7C53A6" }),
  Object.freeze({ id: 208, name: "Eggplant Coloring", hex: "#330033" }),
  Object.freeze({ id: 209, name: "Plum Coloring", hex: "#660066" }),
  Object.freeze({ id: 210, name: "Purple Coloring", hex: "#B200B3" }),
  Object.freeze({ id: 211, name: "Magenta Coloring", hex: "#FF00FF" }),
  Object.freeze({ id: 212, name: "Pink Coloring", hex: "#FF73FF" }),
  Object.freeze({ id: 213, name: "Cottoncandy Coloring", hex: "#FFBFFF" }),
  Object.freeze({ id: 214, name: "Orchid Coloring", hex: "#D98DD9" }),
  Object.freeze({ id: 215, name: "Bruise Coloring", hex: "#A653A6" }),
  Object.freeze({ id: 216, name: "Raisin Coloring", hex: "#330019" }),
  Object.freeze({ id: 217, name: "Tyrian Coloring", hex: "#660033" }),
  Object.freeze({ id: 218, name: "Lust Coloring", hex: "#B30059" }),
  Object.freeze({ id: 219, name: "Fuschia Coloring", hex: "#FF007F" }),
  Object.freeze({ id: 220, name: "Flamingo Coloring", hex: "#FF73B9" }),
  Object.freeze({ id: 221, name: "Valentine Coloring", hex: "#FFBFDF" }),
  Object.freeze({ id: 222, name: "Kobi Coloring", hex: "#D98DB3" }),
  Object.freeze({ id: 223, name: "Rouge Coloring", hex: "#A6537C" }),
  Object.freeze({ id: 224, name: "Black Coloring", hex: "#191919" }),
  Object.freeze({ id: 225, name: "Shadow Coloring", hex: "#333333" }),
  Object.freeze({ id: 226, name: "Charcoal Coloring", hex: "#4D4D4D" }),
  Object.freeze({ id: 227, name: "Gunmetal Coloring", hex: "#666666" }),
  Object.freeze({ id: 228, name: "Slate Coloring", hex: "#808080" }),
  Object.freeze({ id: 229, name: "Steel Coloring", hex: "#999999" }),
  Object.freeze({ id: 230, name: "Grey Coloring", hex: "#B3B3B3" }),
  Object.freeze({ id: 231, name: "Silver Coloring", hex: "#CCCCCC" }),
  Object.freeze({ id: 232, name: "Wisp Coloring", hex: "#E6E6E6" }),
  Object.freeze({ id: 233, name: "White Coloring", hex: "#FFFFFF" }),
  Object.freeze({ id: 234, name: "Mud Coloring", hex: "#403522" }),
  Object.freeze({ id: 235, name: "Bark Coloring", hex: "#594724" }),
  Object.freeze({ id: 236, name: "Brown Coloring", hex: "#80642D" }),
  Object.freeze({ id: 237, name: "Leather Coloring", hex: "#99823D" }),
  Object.freeze({ id: 238, name: "Camel Coloring", hex: "#B39C59" }),
  Object.freeze({ id: 239, name: "Tan Coloring", hex: "#CCB266" }),
  Object.freeze({ id: 240, name: "Sand Coloring", hex: "#E6C973" }),
  Object.freeze({ id: 241, name: "Parchment Coloring", hex: "#FFEFBF" }),
  Object.freeze({ id: 242, name: "Cream Coloring", hex: "#F5F5DC" }),
  Object.freeze({ id: 243, name: "Brick Coloring", hex: "#994326" }),
  Object.freeze({ id: 244, name: "Tangerine Coloring", hex: "#FFA424" }),
  Object.freeze({ id: 245, name: "Gold Coloring", hex: "#FFC000" }),
  Object.freeze({ id: 246, name: "Mustard Coloring", hex: "#F0F032" }),
  Object.freeze({ id: 247, name: "Craggy-Dew Coloring", hex: "#B3E912" }),
  Object.freeze({ id: 248, name: "Grass Coloring", hex: "#227330" }),
  Object.freeze({ id: 249, name: "Stream Coloring", hex: "#2AC6B6" }),
  Object.freeze({ id: 250, name: "Marine Coloring", hex: "#007189" }),
  Object.freeze({ id: 251, name: "Haze Coloring", hex: "#535872" }),
  Object.freeze({ id: 252, name: "Dusk Coloring", hex: "#8F4EA5" }),
  Object.freeze({ id: 253, name: "Thistle Coloring", hex: "#E6C3DD" }),
  Object.freeze({ id: 254, name: "Bubblegum Coloring", hex: "#FFBFCF" })
]);
